# Generated by Django 4.0.5 on 2022-09-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_alter_news_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название режима')),
                ('abbr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rules', models.TextField(verbose_name='Правила')),
                ('typo', models.CharField(choices=[('1vs1', 'Одиночный турнир'), ('2vs2', 'Командный турнир'), ('3vs3', 'Командный турнир'), ('4vs4', 'Командный турнир'), ('5vs5', 'Командный турнир')], default='1vs1', max_length=4)),
                ('status', models.CharField(default='Четко', max_length=255, verbose_name='Статус')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата завершения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('table', models.JSONField()),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.mode', verbose_name='Режим')),
                ('players', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Учавствующие игроки')),
                ('teams', models.ManyToManyField(blank=True, null=True, to='main.teams', verbose_name='Учавствующие команды')),
            ],
        ),
    ]
