# Generated by Django 4.0.5 on 2022-09-15 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_news_options'),
        ('tournaments', '0003_alter_tournament_options_alter_tournament_date_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mode',
            options={'verbose_name': 'Режим', 'verbose_name_plural': 'Режимы'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Учавствующие игроки'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, to='main.teams', verbose_name='Учавствующие команды'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='typo',
            field=models.CharField(choices=[('Одиночный турнир', '1vs1'), ('Командный турнир', '2vs2'), ('Командный турнир', '3vs3'), ('Командный турнир', '4vs4'), ('Командный турнир', '5vs5')], default='1vs1', max_length=64, verbose_name='Тип турнира'),
        ),
    ]
