# Generated by Django 4.0.5 on 2022-09-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_mode_options_alter_tournament_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='table',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
