# Generated by Django 4.0.5 on 2022-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['date_start'], 'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='typo',
            field=models.CharField(choices=[(1, '1vs1'), (2, '2vs2'), (3, '3vs3'), (4, '4vs4'), (5, '5vs5')], default='1vs1', max_length=64, verbose_name='Тип турнира'),
        ),
    ]
