# Generated by Django 4.0.5 on 2022-09-16 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_news_options'),
        ('tournaments', '0006_alter_tournament_options_alter_tournament_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='typo',
            field=models.CharField(choices=[('1', '1vs1'), ('2', '2vs2'), ('3', '3vs3'), ('4', '4vs4'), ('5', '5vs5')], default='1vs1', max_length=64, verbose_name='Тип турнира'),
        ),
        migrations.CreateModel(
            name='TournamentAssociationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particapants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
    ]
