# Generated by Django 4.0.5 on 2022-09-16 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_news_options'),
        ('tournaments', '0007_alter_tournament_typo_tournamentassociationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAssociationTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particapants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Игроки играющие в турнире за команду')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams', verbose_name='Команда')),
            ],
        ),
        migrations.DeleteModel(
            name='TournamentAssociationModel',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, to='tournaments.tournamentassociationteams', verbose_name='Учавствующие команды'),
        ),
    ]
