# Generated by Django 4.0.5 on 2022-09-21 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0009_remove_tournament_teams_alter_tournament_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tournament', to=settings.AUTH_USER_MODEL, verbose_name='Учавствующие игроки'),
        ),
        migrations.DeleteModel(
            name='TournamentAssociationTeams',
        ),
    ]
