# Generated by Django 4.0.5 on 2022-09-25 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_tournament_players_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название статуса')),
                ('code', models.CharField(choices=[('OPEN', 'green'), ('CLOSING', 'yellow'), ('CLOSED', 'orange'), ('ENDED', 'red')], default='OPEN', max_length=64, verbose_name='Тип статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='places',
            field=models.SmallIntegerField(default=10, verbose_name='Кол-во мест на турнире'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.status', verbose_name='Статус'),
        ),
    ]
