# Generated by Django 4.0.5 on 2022-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_status_tournament_places_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='min_places',
            field=models.SmallIntegerField(default=15, verbose_name='Mинимальное кол-во участников'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='places',
            field=models.SmallIntegerField(default=15, verbose_name='Кол-во мест на турнире'),
        ),
    ]
