# Generated by Django 4.0.5 on 2022-09-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_min_places_alter_tournament_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('green', 'OPEN'), ('yellow', 'CLOSING'), ('orange', 'CLOSED'), ('red', 'ENDED')], default='green', max_length=64, verbose_name='Тип статуса'),
        ),
    ]
