# Generated by Django 4.0.5 on 2022-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('green', 'OPEN'), ('yellow', 'CLOSING'), ('orange', 'PLAYING'), ('red', 'CLOSED')], default='green', max_length=64, verbose_name='Тип статуса'),
        ),
    ]
