# Generated by Django 4.0.5 on 2022-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_tournament_is_published_alter_tournament_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.TextField(verbose_name='Правила'),
        ),
    ]
