# Generated by Django 4.0.5 on 2022-10-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_tournament_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='priority',
            field=models.SmallIntegerField(default=1, unique=True, verbose_name='Приоритет'),
            preserve_default=False,
        ),
    ]
