# Generated by Django 4.0.5 on 2022-07-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение')),
                ('data', models.FileField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Файл')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='URL')),
            ],
        ),
    ]
