# Generated by Django 4.0.5 on 2022-09-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AddField(
            model_name='position',
            name='priority',
            field=models.SmallIntegerField(default=1, unique=True, verbose_name='Приоритет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clan', verbose_name='Клан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.limit', verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.position', verbose_name='Должность'),
        ),
    ]
