# Generated by Django 4.0.5 on 2022-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clan',
            options={'ordering': ['id'], 'verbose_name': 'Клан', 'verbose_name_plural': 'Кланы'},
        ),
        migrations.AddField(
            model_name='clan',
            name='maximum',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Максимум игроков'),
        ),
        migrations.AlterField(
            model_name='position',
            name='priority',
            field=models.SmallIntegerField(help_text='Чем ниже приоритет тем главнее должность', unique=True, verbose_name='Приоритет'),
        ),
    ]
