# Generated by Django 4.0.5 on 2022-09-11 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_slug_alter_user_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bronze',
            field=models.IntegerField(default=0, verbose_name='Третьих мест'),
        ),
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.IntegerField(default=0, verbose_name='Первых мест'),
        ),
        migrations.AddField(
            model_name='user',
            name='silver',
            field=models.IntegerField(default=0, verbose_name='Вторых мест'),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Команды',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teams', verbose_name='Команда'),
        ),
    ]
