# Generated by Django 4.0.5 on 2022-09-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_tournament_teams_alter_tournament_players'),
        ('main', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='teams', to='tournaments.tournament', verbose_name='Участие в турнирах'),
        ),
    ]
