# Generated by Django 4.0.5 on 2022-09-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_limit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='about/videos/', verbose_name='Видео')),
                ('para1', models.TextField(verbose_name='Параграф 1-й')),
                ('para2', models.TextField(blank=True, verbose_name='Параграф 2-й')),
            ],
            options={
                'verbose_name': 'О клане',
                'verbose_name_plural': 'О клане',
            },
        ),
        migrations.CreateModel(
            name='AboutPagePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about/images/', verbose_name='Фото')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.aboutpagemodel')),
            ],
            options={
                'verbose_name': 'Фото для слайдера',
                'verbose_name_plural': 'Фото для слайдера',
            },
        ),
    ]
