# Generated by Django 4.0.5 on 2022-09-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_aboutpagemodel_aboutpagephotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagephotos',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='main.aboutpagemodel'),
        ),
    ]
