# Generated by Django 4.0.5 on 2022-10-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_aboutpagephotos_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limit',
            options={'ordering': ['id'], 'verbose_name': 'Лимит', 'verbose_name_plural': 'Ограничения'},
        ),
        migrations.AlterField(
            model_name='teams',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лидер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активирован аккаунт'),
        ),
    ]
