# Generated by Django 4.0.5 on 2022-10-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_limit_options_alter_teams_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
